/* Para cargar productos cambiar extensión a jsx, desde App se importan la funcion y el array y luego se llama a la función desde el componente. Cuidado porque si se renderiza dos veces se cargan de nuevo los productos con ids distintos. */

import { db, products } from "../../firebase/firebase";
import { addDoc, collection } from "firebase/firestore";

export const cymbals = [
    {   avSizes: ['20','22'],
        image: '/cymbalsimg/zildjian/fxcymbs/OrientalDoom.webp',
        title: 'FX Oriental Crash of Doom',
        brand: 'zildjian',
        series: 'doom',
        type: 'fxcymbs',
        description: `Monstrous, explosive FX cymbal that delivers booming trash crashes, dry stick sound, and a broad sustain rich with dark, exotic overtones.`,
        price: 100,
        stock: 4,
    },
    {   avSizes: ['14','17','19'],
        image: '/cymbalsimg/zildjian/fxcymbs/KChina.webp',
        title: 'K China',
        brand: 'zildjian',
        series: 'k',
        type: 'fxcymbs',
        description: `Spectacular dark, low-pitched chinas for exotic special effects.`,
        price: 100,
        stock: 4,
    },
    {   avSizes: ['17'],
        image: '/cymbalsimg/zildjian/fxcymbs/KCustomDarkChina.webp',
        title: 'K Custom Dark China',
        brand: 'zildjian',
        series: 'k custom',
        type: 'fxcymbs',
        description: `Dry, dark China sound. Immediate initial trashy attack with fast decay.`,
        price: 100,
        stock: 4,
    },
    {   avSizes: ['10','14','16','18','20'],
        image: '/cymbalsimg/zildjian/fxcymbs/ACustomEFX.webp',
        title: 'A Custom EFX',
        brand: 'zildjian',
        series: 'a custom',
        type: 'fxcymbs',
        description: `The unique laser cut-out EFX pattern adds a dry crash quality to this bright A Custom cymbal. A "must have" add-on for special effect crashes or cymbal stacking.`,
        price: 100,
        stock: 4,
    },
    {   avSizes: ['10','12','14','16','18','20'],
        image: '/cymbalsimg/zildjian/fxcymbs/FXChinaTrash.webp',
        title: 'FX Oriental China Trash',
        brand: 'zildjian',
        series: 'oriental',
        type: 'fxcymbs',
        description: `Bright, "trashy" China effect for short, explosive accents. Blend into other splash setups or stretch your FX sounds by cymbal stacking.`,
        price: 100,
        stock: 4,
    },
    {   avSizes: ['20','22'],
        image: '/cymbalsimg/zildjian/rides/KConstantinopleRide.webp',
        title: 'K Constantinople Bounce Ride',
        brand: 'zildjian',
        type: 'rides',
        series: 'k constantinople',
        description: `The K Constantinople Bounce Ride is the result of a collaboration with jazz artist Kenny Washington, and recreates the specs of an old, classic K gifted to him in the 1970's by late jazz great Mel Lewis. While replicating the higher curvature and narrower, wider spaced lathing style, a new cup design was created to best resemble that of Kenny's old K. Extra 'cluster' hammering, typically found in orchestral cymbals and placed around the cymbal in eight unique clusters, gives the cymbal a lower drone and just enough trash and 'dirt'. This 20" size features slightly smaller hammer clusters and a slightly higher pitch than the 22", with plenty of wash and sustain that rides over the band and cuts through most small-to-big band settings.`,
        price: 100,
        stock: 0,
    },
    {   avSizes: ['20','22'],
        image: '/cymbalsimg/zildjian/rides/ACustomRide.webp',
        title: 'A Custom Ride',
        brand: 'zildjian',
        type: 'rides',
        series: 'a custom',
        description: `Clear stick definition, yet with a good degree of colorful, warmer undertones.`,
        price: 100,
        stock: 2,
    },
    {   avSizes: ['22','24'],
        image: '/cymbalsimg/zildjian/rides/KLightRide.webp',
        title: 'K Light Ride',
        brand: 'zildjian',
        type: 'rides',
        series: 'k light',
        description: `K Light Rides produce a beautifully dark, smoky sound with excellent stick definition. Play the 22” for a brighter, more controlled sound, or size up to a 24” for a lower pitch and wider spread of dark, colorful overtones.`,
        price: 100,
        stock: 2,
    },
    {   avSizes: ['21','23'],
        image: '/cymbalsimg/zildjian/rides/KSweetRide.webp',
        title: 'K Sweet Ride',
        brand: 'zildjian',
        type: 'rides',
        series: 'k sweet',
        description: `K Sweet Rides take the traditional K sound and brings it in an alternative direction with fresh tonal colors.`,
        price: 100,
        stock: 1,
    },
    {   avSizes: ['20','22'],
        image: '/cymbalsimg/zildjian/rides/KRide.webp',
        title: 'K Ride',
        brand: 'zildjian',
        type: 'rides',
        series: 'k',
        description: `Clear, full-stick definition. Low overtones.`,
        price: 100,
        stock: 3,
    },
    {   avSizes: ['16','17','19','20'],
        image: '/cymbalsimg/zildjian/crashes/KSweetCrash.webp',
        title: 'K Sweet Crash',
        brand: 'zildjian',
        series: 'k sweet',
        type: 'crashes',
        description: `K Sweet Crashes take the traditional K sound and brings it in an alternative direction with fresh tonal colors.`,
        price: 100,
        stock: 0,
    },
    {   avSizes: ['14','15','16','17','19','20'],
        image: '/cymbalsimg/zildjian/crashes/ACustomCrash.webp',
        title: 'A Custom Crash',
        brand: 'zildjian',
        series: 'a custom',
        type: 'crashes',
        description: `Bright, sweet-sounding crash that speaks very quickly. One of the most in-demand crash cymbal sounds for both studio and live settings.`,
        price: 100,
        stock: 3,
    },
    {   avSizes: ['16','17','19','20'],
        image: '/cymbalsimg/zildjian/crashes/AThinCrash.webp',
        title: 'A Thin Crash',
        brand: 'zildjian',
        series: 'a',
        type: 'crashes',
        description: `Fast, bright and responsive thin crash cymbals that respond quickly with plenty of wash.`,
        price: 100,
        stock: 4,
    },
    {   avSizes: ['16','17','19','20'],
        image: '/cymbalsimg/zildjian/crashes/KCustomSpecialDryCrash.webp',
        title: 'K Custom Special Dry Crash',
        brand: 'zildjian',
        series: 'k custom special dry',
        type: 'crashes',
        description: `K Custom Special Dry are the original dry cymbal remastered for today's modern musical styles. These raw and earthy cymbals deliver a dry, funky sound with a quick fast attack, lots of dirt, yet shuts down quickly for a powerful expression of personality.`,
        price: 100,
        stock: 3,
    },
    {   avSizes: ['16','17','19','20'],
        image: '/cymbalsimg/zildjian/crashes/AMediumThinCrash.webp',
        title: 'A Medium Thin Crash',
        brand: 'zildjian',
        series: 'a',
        type: 'crashes',
        description: `Bright-sounding crash in an incredibly versatile and responsive medium-thin weight, with a stronger high-end than the Thin Crash.`,
        price: 100,
        stock: 3,
    },
    {   avSizes: ['16','17','19','20'],
        image: '/cymbalsimg/zildjian/crashes/KCustomDarkCrash.webp',
        title: 'K Custom Dark Crash',
        brand: 'zildjian',
        series: 'k custom dark',
        type: 'crashes',
        description: `The dark and full-bodied K Custom Dark Crash utilizes a special over-hammering technique that allows for a quick and bright attack with an extra fast decay. This allows for a heavier Crash to have a similar response to a thinner and lighter cymbal, but with a lot more volume potential.`,
        price: 100,
        stock: 3,
    },
    {   avSizes: ['14','15'],
        image: '/cymbalsimg/zildjian/hihats/KFatHH.webp',
        title: 'K Fat Hi Hat',
        brand: 'zildjian',
        series: 'k fat',
        type: 'hihats',
        description: `Fat Hats were born out of an inspiration to combine bright and dark manufacturing techniques for a truly blended sound made for any stage or session.`,
        price: 100,
        stock: 2,
    },
    {   avSizes: ['14'],
        image: '/cymbalsimg/zildjian/hihats/ACustomHH.webp',
        title: 'A Custom Hi Hat',
        brand: 'zildjian',
        series: 'a custom',
        type: 'hihats',
        description: `Light, crisp, subtle, very colorful. Delicate stick sound with clean "chick".`,
        price: 100,
        stock: 2,
    },
    {   avSizes: ['14','15','16'],
        image: '/cymbalsimg/zildjian/hihats/AvedisHH.webp',
        title: 'A Avedis Hi Hat',
        brand: 'zildjian',
        series: 'a avedis',
        type: 'hihats',
        description: `A Avedis HiHats are made thinner in weight, and finished with an "aged" patina to re-create the look and sound of vintage A Zildjian cymbals.`,
        price: 100,
        stock: 2,
    },
    {   avSizes: ['13','14'],
        image: '/cymbalsimg/zildjian/hihats/KCustomDarkHH.webp',
        title: 'K Custom Dark Hi Hat',
        brand: 'zildjian',
        series: 'k custom dark',
        type: 'hihats',
        description: `Warm, full-bodied tone with clean stick sound. Fast, bright "chick" that cuts through.`,
        price: 100,
        stock: 0,
    },
    {   avSizes: ['14','15','16'],
        image: '/cymbalsimg/zildjian/hihats/KLightHH.webp',
        title: 'K Light Hi Hat',
        brand: 'zildjian',
        series: 'k Light',
        type: 'hihats',
        description: `Based on requests from players for a lighter weight version of our heralded K Hi-Hats, these K Light Hi-Hats have a medium thin top paired with a medium bottom to give them a dark and slightly delicate feel with a light blend of overtones. Good for most applications including rock, pop, country, and jazz.`,
        price: 100,
        stock: 8,
    },
    {   avSizes: ['14','15','16'],
        image: '/cymbalsimg/zildjian/hihats/KSweetHH.webp',
        title: 'K Sweet Hi Hat',
        brand: 'zildjian',
        series: 'k sweet',
        type: 'hihats',
        description: `K Sweet Hi-Hats take the traditional K sound and brings it in an alternative direction with fresh tonal colors.`,
        price: 100,
        stock: 5,
    },
]

export const cargarDocs = async (productList) => {
    const productsCollection = collection(db, products)
    const addDocument = async (item) => {
        await addDoc(productsCollection, item)
    }
    
    productList.forEach((product) => {
        addDocument(product)
    })
}

